### ISSUE TITLE
make file checking code clear

### ISSUE THREAD

**Issue by cheyilin** [hiein2012/fops#2]
```go
// if file exists
if stat, err := os.Stat(filename); err == nil {
    // if file is a directory
    if stat.IsDir() {
        fmt.Println("error: Expected File got directory " + filename)
    } else if error == nil {
        // Create new Scanner.
        scanner := bufio.NewScanner(fileResult)
        result := 0
        // Use Scan.
        for scanner.Scan() {
            result++
        }
        fmt.Println(result)
    } else {
        fmt.Println(error)
    }
    // if file does *not* exist
} else if os.IsNotExist(err) {
    fmt.Println("error: No such file " + filename)
} else {
    // Schrodinger: file may or may not exist. See err for details.
    // Therefore, do *NOT* use !os.IsNotExist(err) to test for file existence
}
```

Please revise the if-else statement in `fops.go`, refer to [Writing clean if else statements](https://www.geeksforgeeks.org/writing-clean-else-statements/).

Some additional suggestions below:
- Use [`FileMode`](https://golang.org/pkg/os/#FileMode) to check the file/dir
- There should not be such *Schrodinger* case here, never copy the snippet from stackoverflow directly, check the [godoc](https://golang.org/pkg/os/#example_IsNotExist) first.

**Comment by hiein2012** [comment]
Already revised the if/else statements with cleaner code . Please check the latest commit .Thank you.

**Comment by cheyilin** [comment]
Looks good!
