### ISSUE TITLE
binary file detection

### ISSUE THREAD

**Issue by cheyilin** [hiein2012/fops#3]
Please check the [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) and find a way to detect non-text files.

**Comment by hiein2012** [comment]
Thank you for your advice. The latest commit already increased function `CheckFileIsBinary` to detect  binary file. Please check it.

**Comment by cheyilin** [comment]
Thanks, please revise the README and put a binary file in repository for testing and demonstration.

**Comment by hiein2012** [comment]
Already revised the README and uploaded the binary file.

**Comment by cheyilin** [comment]
looks good, thanks!
